language:
  - python3.6
  - python3.7
os: osx
branches:
  only:
  - master
before_install:
- pip3 install --upgrade pip
install:
- pip3 install -r requirements.txt
- pip3 install pylint
script:
# TODO:
#- ./scripts/pylint.sh
- ./scripts/doctests.sh
after_sucess:
- CODECLIMATE_REPO_TOKEN=b686cb85d6a2fc7c7917307a36fd14fe95d1826 codeclimate-test-reporter
