language:
  - python3.6
  - python3.7
os: osx
branches:
  only:
  - master
before_install:
- pip3 install --upgrade pip
install:
# TODO: move to requirements.txt.
- pip3 install libsass
- pip3 install fontTools
- pip3 install markdown
- pip3 install pylint
- pip3 install pyobjc
- pip3 install svgwrite
- pip3 install SimpleIDML
- pip3 install booleanOperations
- pip3 install tornado
- pip3 install SimpleIDML
- pip3 install flat
- python3 setup.py install # PageBot itself.
- wget https://github.com/typesupply/vanilla/archive/master.zip
- unzip master.zip
- cd vanilla-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r vanilla-master
- wget https://github.com/typesupply/defconAppKit/archive/master.zip
- unzip master.zip
- cd defconAppKit-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r defconAppKit-master
- wget https://github.com/typemytype/drawbot/archive/master.zip
- unzip master.zip
- cd drawbot-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r drawbot-master
- wget https://github.com/typesupply/compositor/archive/master.zip
- unzip master.zip
- cd compositor-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r compositor-master
- wget https://github.com/PageBot/PageBotCocoa/archive/master.zip
- unzip master.zip
- cd PageBotCocoa-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r PageBotCocoa-master
- wget https://github.com/PageBot/PageBot/archive/master.zip
- unzip master.zip
- cd PageBot-master
- python3 setup.py install
- cd ..
- rm master.zip
- rm -r PageBot-master
script:
# TODO: move to pytest script.
- mkdir _export
- export WONT_FIX=invalid-name,bad-indentation,trailing-newlines,wrong-import-position,fixme,c-extension-no-member
- export CATCHALL_MAY_FIX_LATER=line-too-long,trailing-whitespace,duplicate-code,bad-whitespace,no-name-in-module,import-error,multiple-imports,bad-continuation,no-value-for-parameter,too-many-arguments,too-many-locals,unused-argument,pointless-string-statement,using-constant-test,invalid-encoded-data,too-many-instance-attributes,too-few-public-methods,attribute-defined-outside-init,protected-access,wrong-import-order,missing-final-newline,mixed-indentation,unused-variable,no-member,too-many-function-args,unexpected-keyword-arg,bare-except,no-self-use,no-method-argument,function-redefined,too-many-public-methods,anomalous-backslash-in-string,redefined-builtin,too-many-branches,relative-import,arguments-differ,syntax-error,reimported,used-before-assignment,too-many-boolean-expressions,too-many-statements,no-self-argument,unnecessary-pass,keyword-arg-before-vararg,not-a-mapping,multiple-statements,inconsistent-return-statements,pointless-statement,ungrouped-imports,unnecessary-semicolon,no-else-return,old-style-class,too-many-nested-blocks,unsubscriptable-object,too-many-lines,unidiomatic-typecheck,bare-except,simplifiable-if-statement,too-many-return-statements,blacklisted-name,exec-used,not-callable,eval-used,empty-docstring,super-init-not-called,singleton-comparison,unreachable,expression-not-assigned,consider-using-enumerate,unbalanced-tuple-unpacking,global-statement,duplicate-key,anomalous-unicode-escape-in-string,no-init,redefined-argument-from-local,broad-except,missing-docstring,superfluous-parens,wildcard-import,unused-wildcard-import,redefined-outer-name,consider-iterating-dictionary,invalid-unary-operand-type
- export PYLINT="pylint --disable=$WONT_FIX,$CATCHALL_MAY_FIX_LATER"
- $PYLINT Lib/pagebotcocoa/
- python3 Lib/pagebotcocoa/contexts/drawbot/drawbotcontext.py
- python3 Lib/pagebotcocoa/contexts/drawbot/drawbotstring.py

after_sucess:
- CODECLIMATE_REPO_TOKEN=b686cb85d6a2fc7c7917307a36fd14fe95d1826 codeclimate-test-reporter
